const SITE_URL = "https://athomecomfortliving.com";

export function absoluteUrl(pathname = "/") {
  return new URL(pathname, SITE_URL).toString();
}

// Metadata is generated by App Router pages; keep structured data beside content.
export default function SEO({ pathname, jsonLd = [] }) {
  return jsonLd.map((schema, index) => (
    <script key={`${pathname}-schema-${index}`} type="application/ld+json"
      dangerouslySetInnerHTML={{ __html: JSON.stringify(schema).replace(/</g, "\\u003c") }} />
  ));
}
